---
title: "02-demographic-data-AB"
output: html_document
date: "2026-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
require(tidyverse)
```


```{r}
sessionInfo()
```
```{r}
crab.dat <- read.csv(file = "../data/time-to-right.csv", header = TRUE)
```
```{r}
crab.dat %>% 
  group_by(tank) %>% 
  summarize(mean.tank.weight = mean(weight, na.rm = TRUE)) #finding the mean weight for each tank
```
```{r}
crab.dat %>% 
  group_by(tank) %>% 
  count(sex = "M" , "F") #counting how many males and females are in each tank
```
```{r} 
#counting how many of each integument color exist
crab.dat %>% 
  group_by(integument.color) %>% 
  count(integument.color) 
```
```{r}
#manually counting the percentages for integument colors
BGper <- (6 / 805) * 100
Gper <- (72 / 805) * 100
Oper <- (74 / 805) * 100
Yper <- (371 / 805) * 100
YGper <- (193 / 805) * 100
YOper <- (89 / 805) * 100
```
```{r}
#adding a column for the average right times
crab.dat %>% 
  rowwise() %>% 
  mutate(., avgTime = mean(c(trial.1, trial.2, trial.3)))
```
```{r}
#filtering for specific 5C treatment
treatment5 <- crab.dat %>% 
  filter(., tank == "T1" | tank == "T4" | tank == "T7")
```
```{r}
#filtering for specific 15C treatment
treatment15 <- crab.dat %>% 
  filter(., tank == "T2" | tank == "T5" | tank == "T8")
```
```{r}
#filtering for specific 25C treatment
treatment25 <- crab.dat %>% 
  filter(., tank == "T3" | tank == "T6" | tank == "T9")
```
```{r}
str(treatment5)
```
```{r}
#average weight per treatment
treatment5 %>% 
  summarize(mean5 = mean(weight, na.rm = TRUE))
treatment15 %>% 
  summarize(mean15 = mean(weight, na.rm = TRUE))
treatment25 %>% 
  summarize(mean25 = mean(weight, na.rm = TRUE))
```
```{r}
crab.meta <- read.csv(file = "../data/crab-metadata.csv", header = TRUE)
# loading in the metadata to add the extra carapace width column
```
```{r}
# trimming dataset to only contain the carapace width
crab.meta$weight <- NULL
crab.meta$integument.color <- NULL
crab.meta$notes <- NULL
crab.meta$dead.date <- NULL
crab.meta$respirometry <- NULL
```
```{r}
crab.meta <- crab.meta %>% 
  rename(crab.ID = ID)
# trying to rename ID to crab.ID for join function
```
```{r}
# combining the two datasets
crab.dat.main <- inner_join(crab.dat, crab.meta, by = "crab.ID")
```
```{r}
#filtering for specific 5C treatment but better
treatment5 <- crab.dat.main %>% 
  filter(., tank.x == "T1" | tank.x == "T4" | tank.x == "T7")
```
```{r}
#filtering for specific 15C treatment but better 
treatment15 <- crab.dat.main %>% 
  filter(., tank.x == "T2" | tank.x == "T5" | tank.x == "T8")
```
```{r}
#filtering for specific 25C treatment but better
treatment25 <- crab.dat.main %>% 
  filter(., tank.x == "T3" | tank.x == "T6" | tank.x == "T9")
```
```{r}
# viewing the treatment to make sure it worked
str(treatment5)
```
```{r}
# trimmming the main dataset again to only have what I need
crab.dat.main$tank.y <- NULL
crab.dat.main$sex.y <- NULL
crab.dat.main$notes <- NULL
crab.dat.main$probe.number <- NULL
crab.dat.main$missing.non.sampled <- NULL
crab.dat.main$missing.swimmer <- NULL
```
```{r}
#finding average carapace width per treatment 
treatment5 %>% 
  summarize(mean5w = mean(carapace.width, na.rm = TRUE))
treatment15 %>% 
  summarize(mean15w = mean(carapace.width, na.rm = TRUE))
treatment25 %>% 
  summarize(mean25w = mean(carapace.width, na.rm = TRUE))
```
```{r}
# adding the total mean weight as an entire column for each treatment
treatment5 <- treatment5 %>% 
  mutate(mean5w = mean(carapace.width, na.rm = TRUE))
treatment15 <- treatment15 %>% 
  mutate(mean15w = mean(carapace.width, na.rm = TRUE))
treatment25 <- treatment25 %>% 
  mutate(mean25w = mean(carapace.width, na.rm = TRUE))
```
```{r}
# trimming the 5c treatment dataset
treatment5$tank.y <- NULL
treatment5$`(mean5w = mean(carapace.width, na.rm = TRUE))` <- NULL
treatment5$notes <- NULL
treatment5$sex.y <- NULL
treatment5$number.legs <- NULL
treatment5$probe.number <- NULL
treatment5$missing.non.sampled <- NULL
treatment5$probe.number <- NULL
treatment5$number <- NULL

# trimming the 15c treatment dataset
treatment15$tank.y <- NULL
treatment15$notes <- NULL
treatment15$sex.y <- NULL
treatment15$number.legs <- NULL
treatment15$probe.number <- NULL
treatment15$missing.non.sampled <- NULL
treatment15$probe.number <- NULL
treatment15$number <- NULL

# trimming the 25c treatment dataset
treatment25$tank.y <- NULL
treatment25$notes <- NULL
treatment25$sex.y <- NULL
treatment25$number.legs <- NULL
treatment25$probe.number <- NULL
treatment25$missing.non.sampled <- NULL
treatment25$probe.number <- NULL
treatment25$number <- NULL

```
```{r}
# getting the average trial times for the main dataset
crab.dat.main <- crab.dat.main %>% 
  rowwise() %>% 
  mutate(., avgTime = mean(c(trial.1, trial.2, trial.3)))
```
```{r}
#trying to get the counts in one nice line of code
simple.output.summary <- crab.dat.main %>% 
  group_by(treatment , sex.x) %>% 
  summarize(count = n(), 
            mean.weight = mean(weight), 
            mean.carapace.width = mean(carapace.width))
```
```{r}
#exporting the dataset I created
write.csv(simple.output.summary, file = "../output/02-demographic-data/AB_simple_output_summary.csv", row.names = TRUE)
```
```{r}
crab.dat.main$integument.color
```
```{r}
#trying to get the integument percentages in an easier way
percentages.inegument.color <- crab.dat.main %>% 
  group_by(integument.color) %>% 
  summarize(count = n()) %>% 
  mutate(Percents = count / sum(count) * 100)
```
```{r}
full.summary <- crab.dat.main %>% 
  group_by(treatment , sex.x , integument.color) %>% 
  summarize(count = n(), 
            mean.weight = mean(weight), 
            mean.carapace.width = mean(carapace.width))
```
```{r}
#cleaning up some extra datasets
rm(percentages.i.c)
rm(percentages.i.c.2)
```
```{r}
# adding the date and getting the time dataset
crab.dat.main <- crab.dat.main %>% 
    mutate(., day = case_when(date == "6/28/23" ~ 0,
                            date == "6/29/23" ~ 1,
                            date == "7/3/23" ~ 2,
                            date == "7/5/23" ~ 7,
                            date == "7/10/23" ~ 12, 
                            date == "7/12/23" ~ 14,
                            date == "7/17/23" ~ 19,
                            date == "7/19/23" ~ 21,
                            date == "7/24/23" ~ 26,
                            date == "7/26/23" ~ 28,
                            date == "8/9/23" ~ 42,
                            date == "8/16/23" ~ 49))
```
```{r}
# trying to make the figures, only first 2
crab.dat.main %>% ggplot(., aes(x = as.character(day), y = avgTime, color = treatment)) + geom_boxplot() + labs(x = "Timepoint (Day)", y = "Average Righting Response (s)") + theme_classic()
```




