---
title: "06f-gene-expression.Rmd"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# requiring the required code
require(tidyverse)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("DESeq2")
library(DESeq2)
library(ggplot2)
```

```{r}
# importing the dataset for MAC
require(tidyverse)
salmon.data <- read.delim("../../../Downloads/salmon.genes.counts.matrix", header=TRUE , check.names = FALSE)
```
```{r}
# importing dataset for WINDOWS
require(tidyverse)
salmon.data <- read.delim("../../../../Downloads/salmon.genes.counts.matrix", header=TRUE , check.names = FALSE)
```

```{r}
colnames(salmon.data)[1] <- "ID"
head(salmon.data)
```
```{r}
#importing the other dataset on MAC
Sequencing.Picks <- read.csv("../metadata/metabolomics-sample-list.csv")
sequencing.picks.8.9.23 <- Sequencing.Picks %>% 
  filter(date == "8/9/23")
```

# removing contaminated sequences
```{r}
contamSeqBlast <- read.delim("../output/06d-blast/contam-list.txt", header = FALSE, check.names = FALSE, col.names = "ID") %>%
  mutate(ID = gsub(pattern = ">", replacement = "", x = ID)) %>%
  mutate(ID = gsub(pattern = "_i.", replacement = "", x = ID)) %>%
  arrange(ID) %>%
  distinct(.)
  #Import list of contaminated sequences. Use gsub to get rid of ">". Use gsub to also get rid of isoform designation (_i = start of isoform, . = any character except new line) so entries can be mapped to gene-level count matrix. Arrange alphanumerically and retain distinct rows.
head(contamSeqBlast) #Confirm changes
nrow(contamSeqBlast) #51785 contaminated genes
```
#modifying end data to remove contaminated sequences
```{r}
End.data <- salmon.data %>% 
  select(ID, any_of(sequencing.picks.8.9.23$crab.ID)) %>% 
  mutate(across(where(is.numeric), round, 0)) %>%
  anti_join(., y = contamSeqBlast, by = "ID") %>% #Use anti-join to return all rows from salmon.data that do not match list of contamination sequences
  arrange(ID)
head(End.data)
nrow(End.data) #597263 genes without contamination
```


```{r}
# making new data subset for end of exp THIS IS WHERE ROW NAMES GETS ADDED(?)
End.data <- salmon.data %>% 
  select(ID, any_of(sequencing.picks.8.9.23$crab.ID)) %>% 
  mutate(across(where(is.numeric), round, 0))
head(End.data)
```
```{r}
head(salmon.data)
```

```{r}
nrow(End.data) #Get initial row count: 913680
End.data <- End.data %>%
  mutate(Total = rowSums(.[, 2:35])) %>%
  filter(!Total==0) %>%
  select(!Total) #Remove rows with 0 counts across all samples
nrow(End.data) #Get final row count: 785006
```
```{r}
head(End.data)
```

#creating the deseq object for the experiment
```{r}
dds.crab <- DESeqDataSetFromMatrix(countData=End.data, 
                              colData=sequencing.picks.8.9.23, 
                              design=~treatment, tidy = TRUE)
```
```{r}
sf.dds.crab <- estimateSizeFactors(dds.crab) #Estimate size factors to determine if we can use VST to transform our data. Size factors should be less than 4 for us to use vst
print(sizeFactors(sf.dds.crab)) #View size factors
all(sizeFactors(sf.dds.crab)) < 4 #True = we can use VST transformation
```
```{r}
gvst <- vst(sf.dds.crab, blind=FALSE) #Apply a variance stabilizing transformation to minimize effects of small counts and normalize wrt library size
head(assay(gvst), 3) #View transformed gene count data for the first three genes in the dataset.
```

```{r}
#priming the code so once error is fixed, it will take about 5 minutes to fix it
crab.stats <- DESeq(dds.crab)
```
```{r}
deseq.results.crab <- results(crab.stats)
head(results(crab.stats, tidy=TRUE))
results.main <- deseq.results.crab[order(deseq.results.crab$padj),]
head(results.main)
```
```{r}
par(mfrow=c(2,3))

plotCounts(crab.stats, gene="TRINITY_DN3052_c0_g1", intgroup="treatment")
plotCounts(crab.stats, gene="TRINITY_DN12380_c0_g1", intgroup="treatment")
#... continue from the graph I made upstairs - intgroup is messing me up
```
```{r}
par(mfrow=c(1,1))
with(deseq.results.crab, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))
with(subset(deseq.results.crab, padj<.01 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(deseq.results.crab, padj<.01 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red")) #negative log2fold = underexpressed/downregulated, visa versa
```
```{r}
plotPCA(gvst, intgroup="treatment") # horizontal is temp-driven changes in gene expression
```

### `arrayQualityMetrics`

```{r}
#e <- ExpressionSet(assay(gvst), AnnotatedDataFrame(as.data.frame(colData(gvst)))) #Generate expression set for outlier identification
#arrayQualityMetrics(e, intgroup = c("condition"), force = T, outdir = "report_for_genes_Loaded") #Identify outliers.

#Based on the report, Apalm_13, (adjacent), Apalm_17 (adjacent), and Apalm_27 (hypoxic) are outliers based on distances between arrays.
```
```{r}
head(deseq.results.crab)
```
```{r}
lfc1.results <- deseq.results.crab %>% 
  as.data.frame() %>% 
  filter(padj < 0.05) %>% 
  filter(abs(log2FoldChange) > 1)
head(lfc1.results)
nrow(lfc1.results) #30188 differentially expressed transcript
```
```{r}
lfc2.results <- deseq.results.crab %>% 
  as.data.frame() %>% 
  filter(padj < 0.05) %>% 
  filter(abs(log2FoldChange) > 2)
head(lfc2.results)
nrow(lfc2.results) #14389 diff expressed transcripts
```
```{r}
count(lfc2.results$log2FoldChange > 0) # 9297 have higher expression at 25C
count(lfc2.results$log2FoldChange < 0) # 5092 have higher expression at 5C
```
```{r}
lfc2.results$ID <- rownames(lfc2.results) #Convert rownames to a new column
head(lfc2.results)
```
#importing annotation list and joining it with the lfc2 results
```{r}
blastAnnotations <- read.delim("../output/06d-blast/blast-results/transcriptome-contam.tab", header = FALSE, check.names = FALSE, ) %>%
  select(1, 13) #Import annotations from blast. Keep only columns 1 and 13
colnames(blastAnnotations) <- c("ID", "annotation") #Rename columns

blastAnnotationsGenes <- blastAnnotations %>%
    mutate(ID = gsub(pattern = "_i.", replacement = "", x = ID)) %>%
  distinct(.) #Remove isoform indication from annotations to match gene-level count matrix and keep only distinct rows. 
head(blastAnnotationsGenes) # 104423 genes remaining
nrow(blastAnnotationsGenes)

lfc2.results.annot <- left_join(x = lfc2.results, y = blastAnnotations, by = "ID") %>%
  distinct(.) #Join to get ref transcript ID information associated with DEGs 
nrow(lfc2.results.annot) # 14389 rows
head(lfc2.results.annot)
```

### new dataset, heatmap, fix PCA